server:
  port: 9011

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 201313
    url: jdbc:postgresql://localhost:5432/hrms_permissionservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}
