server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${postgre}
    url: jdbc:postgresql://localhost:5432/hrms_userservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}


rabbitmq:
  userExchange: userExchange
  register-visitor-queue: registerVisitorQueue
  register-manager-queue: registerManagerQueue
  save-employee-queue: saveEmployeeQueue
  activate-status-queue: activateStatusQueue
  update-user-queue: updateUserQueue
  update-user-bindingKey: updateUserBindingKey
  delete-user-by-authid-bindingKey: deleteUserByAuthidBindingKey
  delete-user-by-authid-queue: deleteUserByAuthidQueue
  delete-auth-by-id-queue: deleteAuthByIdQueue
